### ISSUE TITLE
Add license option for plugin generator

### ISSUE THREAD

**Issue by ashumilova** [eclipse/theia-generator-plugin#6]
As a new plugin author I should have ability to provide the license for my code, so that I will not need to change the default one to the one I need manually. 
The proposed way to handle that - to have no license by default. In case user needs to provide the license - there should be advanced options, where he could input SPDX identifier or the license file location.
For SPDX licenses generation - the following [library](https://github.com/tiaanduplessis/license-o-matic) could be considered or [this one](https://github.com/sergeysova/license.js) or another one :-)

**Comment by benoitf** [comment]
Assigning @mmorhun

**Comment by mmorhun** [comment]
I've looked for a lib for license generation on npmjs and failed to find one which fully suits for ours needs  (`LICENSE` file in the root, headers in the source files and property in the `package.json`) and is compatible by license. So in case of using external lib we need at least two of them, but they always have different set of licenses.
I see two ways here:
 - Use external libs and contribute to them
 - Write code from scratch

To me the second option is preferable, because the logic is not complicated and we won't depend on third party upstream and will have code which does exactly what we need.

**Comment by mmorhun** [comment]
Done.
Use `--license` and `--author` to generate license for plugin.
PR is [here](https://github.com/eclipse/theia-generator-plugin/pull/7).
